version: '3'
services:
  php:
    image: devilbox/php-fpm-8.0:latest
    volumes:
      - ./src:/var/www/html
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./logs:/var/log/nginx
      - ./php8-playground.mmm.conf:/etc/nginx/conf.d/php8-playground.mmm.conf
      - ./src:/var/www/html