version: '3'
services:
  php:
    image: devilbox/php-fpm-8.0:latest
    volumes:
      - ./src:/src
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/src
      - ./php8-playground.mmm.conf:/etc/nginx/conf.d/php8-playground.mmm.conf
      - ./logs:/var/log/nginx